[preprocess]
semeval_data = ""
semeval_output_data = ""

[train-llama]
model=""
output_folder=""
special_token_path = ""
extra_token_path = ""
train_data=""
eval_data=""
learning_rate =
epochs = 
[generate]
output_folder = ""
model_dir = ""
[generate.generation_params]
model_name = ""
gpus = 
batch_size = 
examples_generated = 
max_length = 
temperature =
do_sample= 

[evaluate]
generated_note_path = ""
results_output = ""
model_output=""
processed_dataset_output = ""
i2b2_base_path = ""
semeval_path = ""
mode =