[preprocess]
semeval_data = ""
semeval_output_data = ""

[train-llama]
model=""
output_folder=""
special_token_path = ""
extra_token_path = ""
train_data=""
eval_data=""
learning_rate = 1e-5
epochs = 3
[generate]
output_folder = ""
synthetic_data = ["template", "synonym"] 
[generate.llm]
model_dir = ""
input_file = "data/synthetic"
[generate.llm.generation_params]
model_name = ""
gpus = 1
batch_size = 32
examples_generated = 5
max_length = 256
temperature = 1.2
do_sample= true
[generate.synonym]
dataset = "bc5cdr"
semeval_folder = "data/semeval_split/train"

[evaluate]
generated_note_path = ""
results_output = ""
model_output=""
processed_dataset_output = ""
i2b2_base_path = ""
semeval_path = ""
mode = ""